// <auto-generated />
using System;
using Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260216201305_AAD_nullable_fields")]
    partial class AAD_nullable_fields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.AAD", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndOfLife")
                        .HasColumnType("date");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("NextServiceDue")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("AADs");
                });

            modelBuilder.Entity("Api.Models.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("Api.Models.MainCanopy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MainCanopies");
                });

            modelBuilder.Entity("Api.Models.ReserveCanopy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ReserveCanopies");
                });

            modelBuilder.Entity("Api.Models.Rig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("AADId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MainCanopyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("NextReserveRepackDue")
                        .HasColumnType("date");

                    b.Property<Guid>("ReserveCanopyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AADId")
                        .IsUnique();

                    b.HasIndex("ContainerId")
                        .IsUnique();

                    b.HasIndex("MainCanopyId")
                        .IsUnique();

                    b.HasIndex("ReserveCanopyId")
                        .IsUnique();

                    b.ToTable("Rigs");
                });

            modelBuilder.Entity("Api.Models.Rig", b =>
                {
                    b.HasOne("Api.Models.AAD", "AAD")
                        .WithOne("Rig")
                        .HasForeignKey("Api.Models.Rig", "AADId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Container", "Container")
                        .WithOne("Rig")
                        .HasForeignKey("Api.Models.Rig", "ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.MainCanopy", null)
                        .WithOne("Rig")
                        .HasForeignKey("Api.Models.Rig", "MainCanopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.ReserveCanopy", "ReserveCanopy")
                        .WithOne("Rig")
                        .HasForeignKey("Api.Models.Rig", "ReserveCanopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AAD");

                    b.Navigation("Container");

                    b.Navigation("ReserveCanopy");
                });

            modelBuilder.Entity("Api.Models.AAD", b =>
                {
                    b.Navigation("Rig");
                });

            modelBuilder.Entity("Api.Models.Container", b =>
                {
                    b.Navigation("Rig");
                });

            modelBuilder.Entity("Api.Models.MainCanopy", b =>
                {
                    b.Navigation("Rig");
                });

            modelBuilder.Entity("Api.Models.ReserveCanopy", b =>
                {
                    b.Navigation("Rig");
                });
#pragma warning restore 612, 618
        }
    }
}
